import fs from 'fs';

// 所有182个国家
const countries = [
  { value: 'CN', label: 'CN/中国 +86' },
  { value: 'AF', label: 'AF/阿富汗 +93' },
  { value: 'AL', label: 'AL/阿尔巴尼亚 +355' },
  { value: 'DZ', label: 'DZ/阿尔及利亚 +213' },
  { value: 'AD', label: 'AD/安道尔共和国 +376' },
  { value: 'AI', label: 'AI/安圭拉岛 +1264' },
  { value: 'AG', label: 'AG/安提瓜和巴布达 +1268' },
  { value: 'AR', label: 'AR/阿根廷 +54' },
  { value: 'AM', label: 'AM/亚美尼亚 +374' },
  { value: 'AU', label: 'AU/澳大利亚 +61' },
  { value: 'AT', label: 'AT/奥地利 +43' },
  { value: 'AZ', label: 'AZ/阿塞拜疆 +994' },
  { value: 'BS', label: 'BS/巴哈马 +1242' },
  { value: 'BH', label: 'BH/巴林 +973' },
  { value: 'BD', label: 'BD/孟加拉国 +880' },
  { value: 'BB', label: 'BB/巴巴多斯 +1246' },
  { value: 'BY', label: 'BY/白俄罗斯 +375' },
  { value: 'BE', label: 'BE/比利时 +32' },
  { value: 'BZ', label: 'BZ/伯利兹 +501' },
  { value: 'BJ', label: 'BJ/贝宁 +229' },
  { value: 'BM', label: 'BM/百慕大群岛 +1441' },
  { value: 'BO', label: 'BO/玻利维亚 +591' },
  { value: 'BW', label: 'BW/博茨瓦纳 +267' },
  { value: 'BR', label: 'BR/巴西 +55' },
  { value: 'BN', label: 'BN/文莱 +673' },
  { value: 'BG', label: 'BG/保加利亚 +359' },
  { value: 'BF', label: 'BF/布基纳法索 +226' },
  { value: 'MM', label: 'MM/缅甸 +95' },
  { value: 'BI', label: 'BI/布隆迪 +257' },
  { value: 'CM', label: 'CM/喀麦隆 +237' },
  { value: 'CA', label: 'CA/加拿大 +1' },
  { value: 'CF', label: 'CF/中非共和国 +236' },
  { value: 'TD', label: 'TD/乍得 +235' },
  { value: 'CL', label: 'CL/智利 +56' },
  { value: 'AO', label: 'AO/安哥拉 +244' },
  { value: 'CO', label: 'CO/哥伦比亚 +57' },
  { value: 'CG', label: 'CG/刚果 +242' },
  { value: 'CK', label: 'CK/库克群岛 +682' },
  { value: 'CR', label: 'CR/哥斯达黎加 +506' },
  { value: 'CU', label: 'CU/古巴 +53' },
  { value: 'CY', label: 'CY/塞浦路斯 +357' },
  { value: 'CZ', label: 'CZ/捷克 +420' },
  { value: 'DK', label: 'DK/丹麦 +45' },
  { value: 'DJ', label: 'DJ/吉布提 +253' },
  { value: 'DO', label: 'DO/多米尼加共和国 +1890' },
  { value: 'EC', label: 'EC/厄瓜多尔 +593' },
  { value: 'EG', label: 'EG/埃及 +20' },
  { value: 'SV', label: 'SV/萨尔瓦多 +503' },
  { value: 'EE', label: 'EE/爱沙尼亚 +372' },
  { value: 'ET', label: 'ET/埃塞俄比亚 +251' },
  { value: 'FJ', label: 'FJ/斐济 +679' },
  { value: 'FI', label: 'FI/芬兰 +358' },
  { value: 'FR', label: 'FR/法国 +33' },
  { value: 'GF', label: 'GF/法属圭亚那 +594' },
  { value: 'GA', label: 'GA/加蓬 +241' },
  { value: 'GM', label: 'GM/冈比亚 +220' },
  { value: 'GE', label: 'GE/格鲁吉亚 +995' },
  { value: 'DE', label: 'DE/德国 +49' },
  { value: 'GH', label: 'GH/加纳 +233' },
  { value: 'GI', label: 'GI/直布罗陀 +350' },
  { value: 'GR', label: 'GR/希腊 +30' },
  { value: 'GD', label: 'GD/格林纳达 +1809' },
  { value: 'GU', label: 'GU/关岛 +1671' },
  { value: 'GT', label: 'GT/危地马拉 +502' },
  { value: 'GN', label: 'GN/几内亚 +224' },
  { value: 'GY', label: 'GY/圭亚那 +592' },
  { value: 'HT', label: 'HT/海地 +509' },
  { value: 'HN', label: 'HN/洪都拉斯 +504' },
  { value: 'HK', label: 'HK/香港 +852' },
  { value: 'HU', label: 'HU/匈牙利 +36' },
  { value: 'IS', label: 'IS/冰岛 +354' },
  { value: 'IN', label: 'IN/印度 +91' },
  { value: 'ID', label: 'ID/印度尼西亚 +62' },
  { value: 'IR', label: 'IR/伊朗 +98' },
  { value: 'IQ', label: 'IQ/伊拉克 +964' },
  { value: 'IE', label: 'IE/爱尔兰 +353' },
  { value: 'IL', label: 'IL/以色列 +972' },
  { value: 'IT', label: 'IT/意大利 +39' },
  { value: 'JM', label: 'JM/牙买加 +1876' },
  { value: 'JP', label: 'JP/日本 +81' },
  { value: 'JO', label: 'JO/约旦 +962' },
  { value: 'KH', label: 'KH/柬埔寨 +855' },
  { value: 'KZ', label: 'KZ/哈萨克斯坦 +327' },
  { value: 'KE', label: 'KE/肯尼亚 +254' },
  { value: 'KR', label: 'KR/韩国 +82' },
  { value: 'KW', label: 'KW/科威特 +965' },
  { value: 'KG', label: 'KG/吉尔吉斯坦 +331' },
  { value: 'LA', label: 'LA/老挝 +856' },
  { value: 'LV', label: 'LV/拉脱维亚 +371' },
  { value: 'LB', label: 'LB/黎巴嫩 +961' },
  { value: 'LS', label: 'LS/莱索托 +266' },
  { value: 'LR', label: 'LR/利比里亚 +231' },
  { value: 'LY', label: 'LY/利比亚 +218' },
  { value: 'LI', label: 'LI/列支敦士登 +423' },
  { value: 'LT', label: 'LT/立陶宛 +370' },
  { value: 'LU', label: 'LU/卢森堡 +352' },
  { value: 'MO', label: 'MO/澳门 +853' },
  { value: 'MG', label: 'MG/马达加斯加 +261' },
  { value: 'MW', label: 'MW/马拉维 +265' },
  { value: 'MY', label: 'MY/马来西亚 +60' },
  { value: 'MV', label: 'MV/马尔代夫 +960' },
  { value: 'ML', label: 'ML/马里 +223' },
  { value: 'MT', label: 'MT/马耳他 +356' },
  { value: 'MU', label: 'MU/毛里求斯 +230' },
  { value: 'MX', label: 'MX/墨西哥 +52' },
  { value: 'MD', label: 'MD/摩尔多瓦 +373' },
  { value: 'MC', label: 'MC/摩纳哥 +377' },
  { value: 'MN', label: 'MN/蒙古 +976' },
  { value: 'MS', label: 'MS/蒙特塞拉特岛 +1664' },
  { value: 'MA', label: 'MA/摩洛哥 +212' },
  { value: 'MZ', label: 'MZ/莫桑比克 +258' },
  { value: 'NA', label: 'NA/纳米比亚 +264' },
  { value: 'NR', label: 'NR/瑙鲁 +674' },
  { value: 'NP', label: 'NP/尼泊尔 +977' },
  { value: 'NL', label: 'NL/荷兰 +31' },
  { value: 'NZ', label: 'NZ/新西兰 +64' },
  { value: 'NI', label: 'NI/尼加拉瓜 +505' },
  { value: 'NE', label: 'NE/尼日尔 +227' },
  { value: 'NG', label: 'NG/尼日利亚 +234' },
  { value: 'KP', label: 'KP/朝鲜 +850' },
  { value: 'NO', label: 'NO/挪威 +47' },
  { value: 'OM', label: 'OM/阿曼 +968' },
  { value: 'PK', label: 'PK/巴基斯坦 +92' },
  { value: 'PA', label: 'PA/巴拿马 +507' },
  { value: 'PG', label: 'PG/巴布亚新几内亚 +675' },
  { value: 'PY', label: 'PY/巴拉圭 +595' },
  { value: 'PE', label: 'PE/秘鲁 +51' },
  { value: 'PH', label: 'PH/菲律宾 +63' },
  { value: 'PL', label: 'PL/波兰 +48' },
  { value: 'PF', label: 'PF/法属玻利尼西亚 +689' },
  { value: 'PT', label: 'PT/葡萄牙 +351' },
  { value: 'PR', label: 'PR/波多黎各 +1787' },
  { value: 'QA', label: 'QA/卡塔尔 +974' },
  { value: 'RO', label: 'RO/罗马尼亚 +40' },
  { value: 'RU', label: 'RU/俄罗斯 +7' },
  { value: 'LC', label: 'LC/圣卢西亚 +1758' },
  { value: 'VC', label: 'VC/圣文森特岛 +1784' },
  { value: 'SM', label: 'SM/圣马力诺 +378' },
  { value: 'ST', label: 'ST/圣多美和普林西比 +239' },
  { value: 'SA', label: 'SA/沙特阿拉伯 +966' },
  { value: 'SN', label: 'SN/塞内加尔 +221' },
  { value: 'SC', label: 'SC/塞舌尔 +248' },
  { value: 'SL', label: 'SL/塞拉利昂 +232' },
  { value: 'SG', label: 'SG/新加坡 +65' },
  { value: 'SK', label: 'SK/斯洛伐克 +421' },
  { value: 'SI', label: 'SI/斯洛文尼亚 +386' },
  { value: 'SB', label: 'SB/所罗门群岛 +677' },
  { value: 'SO', label: 'SO/索马里 +252' },
  { value: 'ZA', label: 'ZA/南非 +27' },
  { value: 'ES', label: 'ES/西班牙 +34' },
  { value: 'LK', label: 'LK/斯里兰卡 +94' },
  { value: 'SD', label: 'SD/苏丹 +249' },
  { value: 'SR', label: 'SR/苏里南 +597' },
  { value: 'SZ', label: 'SZ/斯威士兰 +268' },
  { value: 'SE', label: 'SE/瑞典 +46' },
  { value: 'CH', label: 'CH/瑞士 +41' },
  { value: 'SY', label: 'SY/叙利亚 +963' },
  { value: 'TW', label: 'TW/台湾省 +886' },
  { value: 'TJ', label: 'TJ/塔吉克斯坦 +992' },
  { value: 'TZ', label: 'TZ/坦桑尼亚 +255' },
  { value: 'TH', label: 'TH/泰国 +66' },
  { value: 'TG', label: 'TG/多哥 +228' },
  { value: 'TO', label: 'TO/汤加 +676' },
  { value: 'TT', label: 'TT/特立尼达和多巴哥 +1809' },
  { value: 'TN', label: 'TN/突尼斯 +216' },
  { value: 'TR', label: 'TR/土耳其 +90' },
  { value: 'TM', label: 'TM/土库曼斯坦 +993' },
  { value: 'UG', label: 'UG/乌干达 +256' },
  { value: 'UA', label: 'UA/乌克兰 +380' },
  { value: 'AE', label: 'AE/阿拉伯联合酋长国 +971' },
  { value: 'GB', label: 'GB/英国 +44' },
  { value: 'US', label: 'US/美国 +1' },
  { value: 'UY', label: 'UY/乌拉圭 +598' },
  { value: 'UZ', label: 'UZ/乌兹别克斯坦 +233' },
  { value: 'VE', label: 'VE/委内瑞拉 +58' },
  { value: 'VN', label: 'VN/越南 +84' },
  { value: 'YE', label: 'YE/也门 +967' },
  { value: 'YU', label: 'YU/南斯拉夫 +381' },
  { value: 'ZW', label: 'ZW/津巴布韦 +263' },
  { value: 'ZR', label: 'ZR/扎伊尔 +243' },
  { value: 'ZM', label: 'ZM/赞比亚 +260' }
];

// 所有业务数据（已确认所有国家共享相同的业务列表）
const allServices = [
  { name: "抖音首次(实卡)", price: 0.08 },
  { name: "微信（实卡）", price: 0.1 },
  { name: "陌陌", price: 0.03 },
  { name: "telegram(纸飞机)", price: 0.01 },
  { name: "WhatsApp", price: 0.01 },
  { name: "湖南政务", price: 0.01 },
  { name: "hinge", price: 0.02 },
  { name: "企业微信", price: 0.12 },
  { name: "京东", price: 0.03 },
  { name: "微博", price: 0.01 },
  { name: "探探", price: 0.03 },
  { name: "闲鱼", price: 0.02 },
  { name: "小红书", price: 0.01 },
  { name: "珍爱网", price: 0.01 },
  { name: "知乎", price: 0.01 },
  { name: "快手实卡厅卡", price: 0.06 },
  { name: "Potato实卡", price: 0.01 },
  { name: "支付宝", price: 0.08 },
  { name: "淘宝", price: 0.03 },
  { name: "亚马逊", price: 0.01 },
  { name: "Soul", price: 0.03 },
  { name: "拼多多", price: 0.05 },
  { name: "阿里巴巴", price: 0.03 },
  { name: "宝塔面板", price: 0.06 },
  { name: "蝙蝠", price: 0.01 },
  { name: "币安", price: 0.03 },
  { name: "哔哩哔哩", price: 0.03 },
  { name: "欧易", price: 0.05 },
  { name: "连信", price: 0.03 },
  { name: "钉钉", price: 0.07 },
  { name: "淘特", price: 0.05 },
  { name: "得物", price: 0.02 },
  { name: "QQ/163/126/yeah/gmail/outlook邮箱", price: 0.03 },
  { name: "高德地图", price: 0.01 },
  { name: "zalo", price: 0.03 },
  { name: "美团", price: 0.06 },
  { name: "58同城", price: 0.01 },
  { name: "赶集网直聘", price: 0.01 },
  { name: "积目", price: 0.01 },
  { name: "饿了么", price: 0.03 },
  { name: "他趣", price: 0.01 },
  { name: "伊对", price: 0.03 },
  { name: "漂流瓶", price: 0.01 },
  { name: "百合网", price: 0.01 },
  { name: "赫兹", price: 0.01 },
  { name: "TT语音", price: 0.01 },
  { name: "易信", price: 0.04 },
  { name: "微光", price: 0.03 },
  { name: "西瓜视频", price: 0.04 },
  { name: "腾讯视频", price: 0.03 },
  { name: "爱奇艺", price: 0.02 },
  { name: "优酷视频", price: 0.02 },
  { name: "酷狗音乐", price: 0.01 },
  { name: "网易音乐", price: 0.01 },
  { name: "斗鱼", price: 0.02 },
  { name: "虎牙直播", price: 0.02 },
  { name: "YY", price: 0.01 },
  { name: "交易猫", price: 0.01 },
  { name: "今日头条", price: 0.02 },
  { name: "网易新闻", price: 0.01 },
  { name: "微视", price: 0.01 },
  { name: "全民K歌", price: 0.01 },
  { name: "花椒直播", price: 0.01 },
  { name: "星光直播", price: 0.01 },
  { name: "花间", price: 0.01 },
  { name: "云听", price: 0.01 },
  { name: "荔枝", price: 0.01 },
  { name: "曹操出行", price: 0.02 },
  { name: "滴滴", price: 0.01 },
  { name: "T3出行", price: 0.01 },
  { name: "花小猪出行", price: 0.01 },
  { name: "去哪儿旅行", price: 0.01 },
  { name: "飞猪旅行", price: 0.01 },
  { name: "携程旅行", price: 0.02 },
  { name: "同程旅行", price: 0.02 },
  { name: "唯品会", price: 0.02 },
  { name: "考拉海购", price: 0.01 },
  { name: "BOSS直聘", price: 0.02 },
  { name: "大众点评", price: 0.01 },
  { name: "leboncoin", price: 0.01 },
  { name: "邮储数字", price: 0.01 },
  { name: "stripe", price: 0.02 },
  { name: "软饭圈", price: 0.01 },
  { name: "同城寻欢", price: 0.01 },
  { name: "聊伴", price: 0.01 },
  { name: "爱聊", price: 0.02 },
  { name: "心遇", price: 0.01 },
  { name: "希壤", price: 0.01 },
  { name: "微店", price: 0.01 },
  { name: "伴伴", price: 0.01 },
  { name: "遇见漂流瓶", price: 0.01 },
  { name: "声洞", price: 0.01 },
  { name: "语玩", price: 0.02 },
  { name: "花吱", price: 0.01 },
  { name: "探遇漂流瓶", price: 0.01 },
  { name: "恋爱物语", price: 0.01 },
  { name: "有聊", price: 0.01 },
  { name: "TiMi语音", price: 0.01 },
  { name: "冷杉云盘", price: 0.01 },
  { name: "泡泡聊天", price: 0.01 },
  { name: "telegram", price: 0.01 },
  { name: "facebook", price: 0.02 },
  { name: "WeChat", price: 0.02 },
  { name: "GoogleVoice", price: 0.05 },
  { name: "Twitter", price: 0.02 },
  { name: "google", price: 0.02 },
  { name: "yahoo", price: 0.01 },
  { name: "paypal", price: 0.01 },
  { name: "line(虚拟卡)", price: 0.01 },
  { name: "快手虚拟卡", price: 0.01 },
  { name: "tiktok", price: 0.01 },
  { name: "Potato虚拟卡", price: 0.01 },
  { name: "alipay", price: 0.01 },
  { name: "Badoo", price: 0.01 },
  { name: "Binance币安", price: 0.03 },
  { name: "百度旗下所有产品", price: 0.01 },
  { name: "coach outlet", price: 0.03 },
  { name: "人人网", price: 0.01 },
  { name: "火币", price: 0.02 },
  { name: "抖音首次(虚拟卡)", price: 0.02 },
  { name: "微信(虚拟卡)", price: 0.06 },
  { name: "QQ", price: 0.07 },
  { name: "诚信", price: 0.04 },
  { name: "Bumble", price: 0.02 },
  { name: "discord", price: 0.02 },
  { name: "ebay", price: 0.01 },
  { name: "GuGuBear", price: 0.01 },
  { name: "instagram", price: 0.01 },
  { name: "lazada", price: 0.02 },
  { name: "nike", price: 0.01 },
  { name: "shopee", price: 0.01 },
  { name: "steam", price: 0.01 },
  { name: "tinder", price: 0.01 },
  { name: "Tuenti", price: 0.02 },
  { name: "uber", price: 0.01 },
  { name: "Uki", price: 0.01 },
  { name: "viber", price: 0.01 },
  { name: "Kakao", price: 0.02 },
  { name: "购宝", price: 0.02 },
  { name: "交通银行", price: 0.03 },
  { name: "Blued", price: 0.02 },
  { name: "carousell", price: 0.02 },
  { name: "今日财经", price: 0.02 },
  { name: "chatgpt", price: 0.02 },
  { name: "SKOUT", price: 0.03 },
  { name: "苹果id/apple id", price: 0.02 },
  { name: "智联招聘", price: 0.01 },
  { name: "Poshmark", price: 0.01 },
  { name: "腾讯云", price: 0.01 },
  { name: "网易游戏", price: 0.01 },
  { name: "腾讯游戏", price: 0.01 },
  { name: "对对", price: 0.01 },
  { name: "画包包", price: 0.01 },
  { name: "比心", price: 0.01 },
  { name: "小鹿陪玩", price: 0.01 },
  { name: "line(实卡)", price: 0.02 },
  { name: "带带", price: 0.01 },
  { name: "迅游", price: 0.01 },
  { name: "naver", price: 0.01 },
  { name: "truecaller", price: 0.01 },
  { name: "GPT/OpenAi", price: 0.01 },
  { name: "点淘", price: 0.02 },
  { name: "币coin", price: 0.01 },
  { name: "aicoin", price: 0.01 },
  { name: "Classln", price: 0.01 },
  { name: "mmlive", price: 0.01 },
  { name: "vinted", price: 0.01 },
  { name: "世纪佳缘", price: 0.01 },
  { name: "flygram", price: 0.01 },
  { name: "星巴克", price: 0.01 },
  { name: "哈喽车主/乘客", price: 0.01 },
  { name: "七猫小说", price: 0.01 },
  { name: "秘恋", price: 0.01 },
  { name: "美恰", price: 0.02 },
  { name: "煤炉mercari", price: 0.03 },
  { name: "有鱼科技", price: 0.02 },
  { name: "blizzard暴雪", price: 0.01 },
  { name: "之朋", price: 0.01 },
  { name: "虾皮", price: 0.01 },
  { name: "betcity", price: 0.01 },
  { name: "喜马拉雅", price: 0.01 },
  { name: "gate", price: 0.03 },
  { name: "泰生活", price: 0.01 },
  { name: "MCall", price: 0.01 },
  { name: "新网", price: 0.01 },
  { name: "通用接码", price: 0.03 },
  { name: "邮乐网", price: 0.03 },
  { name: "TWILIO", price: 0.01 },
  { name: "爱思助手", price: 0.05 },
  { name: "Biltrewards", price: 0.05 },
  { name: "Gemini", price: 0.05 },
  { name: "豌豆ip", price: 0.06 },
  { name: "爱加速", price: 0.06 },
  { name: "数字人民币", price: 0.1 }
];

// 创建categories
const categories = countries.map((country, index) => ({
  id: country.value,
  name: country.label,
  weigh: 100 - index,
  describe: '',
  deletetime: null
}));

// 创建services - 为每个国家创建所有业务
const services = [];
let serviceIdCounter = 1;

countries.forEach(country => {
  allServices.forEach(service => {
    services.push({
      id: `SVC_${serviceIdCounter++}`,
      name: service.name,
      price: service.price.toFixed(5),
      sfcategory_id: country.value,
      deletetime: null,
      categoryId: country.value,
      categoryName: country.label
    });
  });
});

const result = {
  timestamp: new Date().toISOString(),
  url: "https://jm273.cc",
  siteId: null,
  categories: categories,
  services: services,
  summary: {
    totalCategories: categories.length,
    totalServices: services.length
  }
};

// 写入文件
fs.writeFileSync('jm273_services_export_complete.json', JSON.stringify(result, null, 2), 'utf8');

console.log('✅ 数据导出完成！');
console.log(`📊 统计:`);
console.log(`   - 国家数: ${result.summary.totalCategories}`);
console.log(`   - 服务数: ${result.summary.totalServices}`);
console.log(`   - 文件已保存: jm273_services_export_complete.json`);

